apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MY_SQL_URL: "${MY_SQL_URL}"
  MY_SQL_USER: "${MY_SQL_USER}"
  MY_SQL_PASSWORD: "${MY_SQL_PASSWORD}"
  MONGO_ATLAS_URI: "${MONGO_ATLAS_URI}"
  JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
  CORS_URL: "https://www.bonfire.show"
  S3ACCESS: "${S3ACCESS}"
  S3SECRET: "${S3SECRET}"
  S3ENDPOINT: "${S3ENDPOINT}"
  S3BUCKET: "${S3BUCKET}"
  EMAIL_PASS: "${EMAIL_PASS}"
  